### ISSUE TITLE
提供对tk.mapper  的支持

### ISSUE THREAD

**Issue by d378935454** [fangjinuo/sqlhelper#110]
当前使用的是tk.mapper(通用mapper)，能否提供类似sqlhelper-mybatisplus-spring-boot的sqlhelper-tkmapper-spring-boot.

**Comment by fangjinuo** [comment]
@d378935454 

最近准备对 tk.mapper 进行支持，在 tkmapper 分支里，加了相关的 example，运行 失败，我之前并没有用过 tkmapper，你有空的话先帮我看一下 错误的原因吧。

6c171a2ecb47fff6bac0172d20883fda1820b815

**Comment by fangjinuo** [comment]
@d378935454  已在 3.1.0 版本做了支持
