### ISSUE TITLE
亲啊，希望能增加中文的相关介绍材料

### ISSUE THREAD

**Issue by noear** [fangjinuo/sqlhelper#118]
国内程序员，有不少英文很差。像我就是其中一个。

希望能增加中文的相关介绍材料：）

**Comment by fangjinuo** [comment]
好的

**Comment by fangjinuo** [comment]
在中文的出来之前，委屈你先看看这个：
https://fangjinuo.gitee.io/docs/

**Comment by zwllxs** [comment]
![图片](https://user-images.githubusercontent.com/5228810/80205441-32c3e180-865d-11ea-908e-b687150f08ae.png)
一打开，就看到一错字

**Comment by fangjinuo** [comment]
@zwllxs 多谢提醒，已修复。
