### ISSUE TITLE
有人向我发邮件推荐了这个, 这个是干嘛的啊?

### ISSUE THREAD

**Issue by johnnywjh** [fangjinuo/sqlhelper#122]
这个是一些模块的封装么?   
有没有中文版的介绍?

**Comment by fangjinuo** [comment]
这个是一个sql 工具套装，提供了多种工具，
1)一个是通用分页插件，支持与各位数据库操作框架集成
2)一个是ddl dumper 可以用到各种场景，譬如说版本升级时，对比数据库变化，验证升级脚本等
3)一个是批入插曲执行器，为了做压力测试性能测试之用
4)一个是为mybatis 提供通用的批量更新执行工具
5)还有更多其他的待开发的或者已开发的特性

**Comment by fangjinuo** [comment]
中文文档后续会支持上，敬请期待
