### ISSUE TITLE
com.microsoft.sqlserver.jdbc.SQLServerException: 在 FETCH 语句中选项 FIRST 的用法无效。

### ISSUE THREAD

**Issue by zwllxs** [fangjinuo/sqlhelper#130]
走的spring boot+Mybatis,
原语句:SELECT * FROM user_log
生成的语句:  SELECT * FROM user_log ORDER BY id FETCH FIRST ? ROWS ONLY
数据库为 sqlserver 2008,
我配置的方言为: sqlserver,
能具体指定sqlserver版本吗？

**Comment by fangjinuo** [comment]
首先多谢你这两天提出的问题。
对于SQLServer，各个版本的给加了版本号的指定。目前尚未发布，你可以先自行打包测试一下。
