### ISSUE TITLE
Can't find a suitable or enabled SQL instrumentation

### ISSUE THREAD

**Issue by yaozhigangyeah** [fangjinuo/sqlhelper#131]
最新代码编译后不能用：
com.jn.sqlhelper.dialect.instrument.SQLStatementInstrumentor中
104行            Preconditions.checkNotNull(instrumentation,"Can't find a suitable or enabled SQL instrumentation");检验不通过

**Comment by fangjinuo** [comment]
我刚看了sqlhelper-example, 正常启动呀

**Comment by yaozhigangyeah** [comment]
3.0.2的jar是正常的，我自己打包后启动会报错，我看了3.0.2那个包，比现在最新的代码少了一些类，例sqlhelper-dialect项目里没有com.jn.sqlhelper.dialect.instrument包

**Comment by fangjinuo** [comment]
哦，为了支持更多的特性，底层最近在重构。
master分支上的代码是重构过程中的，但由于没有更新 pom.xml中的版本号（3.0.2已发布，pom中还是 3.0.2）可能是这个原因导致。

现已将pom.xml的版本号更新

**Comment by fangjinuo** [comment]
你在用master的代码是，是不是没有引入sqlhelper-jsqlparser 这个模块 ？

**Comment by fangjinuo** [comment]
参见 [FAQ](https://github.com/fangjinuo/sqlhelper/wiki/FAQ)
