### ISSUE TITLE
不支持exam_type_name like "%"#{examTypeName}"%"

### ISSUE THREAD

**Issue by yaozhigangyeah** [fangjinuo/sqlhelper#135]
3.0.2版本不支持如下模糊匹配
exam_type_name like "%"#{examTypeName}"%"

**Comment by fangjinuo** [comment]
like 中 使用 concat 函数的是支持的，你可以先用这个方式。

对于题目中的方式，待我测试确认后再说

**Comment by fangjinuo** [comment]
![like_concat](https://user-images.githubusercontent.com/8428331/82559985-1e62fe00-9ba3-11ea-8acb-4751f7fafc01.png)

**Comment by fangjinuo** [comment]
你题目中的方式，我尝试不成功（h2数据库），即便是 非分页的，也不会成功
https://blog.csdn.net/m0_37897396/article/details/80237920

**Comment by fangjinuo** [comment]
而bind 方式的，其本质是 将 bind 后的参数整体（% your value%） 作为参数 赋值的。
所以一旦开启了  like 转义，可能会查不到任何数据，不开启 like 转义的话会正常。
