### ISSUE TITLE
多数据源如何配置

### ISSUE THREAD

**Issue by yaozhigangyeah** [fangjinuo/sqlhelper#138]

**Comment by fangjinuo** [comment]
不需要配置，自动识别

**Comment by yaozhigangyeah** [comment]
我这不识别request.getResult()返回为空

**Comment by yaozhigangyeah** [comment]
PagingRequest request = new PagingRequest()
                    .setPageNo(consulationComplaint.getPageNo())
                    .setPageSize(consulationComplaint.getPageSize());
            PagingRequestContextHolder.getContext().setPagingRequest(request);
            consulationComplaintMapper.findApplyingInfo(consulationComplaint);

**Comment by HSPCode** [comment]
你好，最近使用springboot+dynamic适配多数据源，但是SQLHelper好像并不支持多数据源呢。拼接分页sql语句的处理是Dialect的LimitHandler类，但是这个类是根据org.apache.ibatis.session.Configuration类的databaseId获取的，问题就在于databaseId在项目启动的时候会初始化，dynamic配置了多个数据源，默认取第一个配置的当做databaseId（问题概括，dynamic配置两个数据源，第一个是mysql，第二个是oracle。使用startPage时，全是按照第一个配置的数据源mysql的语法进行处理）。请问下，这个问题怎么处理呢？

**Comment by fangjinuo** [comment]
我想的配置多数据源，其实就是创建多个sqlsessionfactory，每个session factory里对应一个condiguration，自然就对应一个sqlhelper插件实例了。

你说的dynamic是mybatis-plus里提供的吗，如果是的话，我给研究一下，看看怎么配置。

**Comment by HSPCode** [comment]
您好，是dynamic-datasource-spring-boot-starter这个依赖提供的多数据源配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fangjinuo/sqlhelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 上午6:53
收件人:&nbsp;"fangjinuo/sqlhelper"<sqlhelper@noreply.github.com&gt;;
抄送:&nbsp;"身高一米八"<907172835@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fangjinuo/sqlhelper] 多数据源如何配置 (#138)





 
我想的配置多数据源，其实就是创建多个sqlsessionfactory，每个session factory里对应一个condiguration，自然就对应一个sqlhelper插件实例了。
 
你说的dynamic是mybatis-plus里提供的吗，如果是的话，我给研究一下，看看怎么配置。

**Comment by HSPCode** [comment]
项目用的mybatis是tk.mybatis，后续会集成为mybatis-plus




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fangjinuo/sqlhelper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 上午6:53
收件人:&nbsp;"fangjinuo/sqlhelper"<sqlhelper@noreply.github.com&gt;;
抄送:&nbsp;"身高一米八"<907172835@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fangjinuo/sqlhelper] 多数据源如何配置 (#138)





 
我想的配置多数据源，其实就是创建多个sqlsessionfactory，每个session factory里对应一个condiguration，自然就对应一个sqlhelper插件实例了。
 
你说的dynamic是mybatis-plus里提供的吗，如果是的话，我给研究一下，看看怎么配置。

**Comment by fangjinuo** [comment]
@HSPCode 

昨晚加了一个参数，来控制是否从org.apache.ibatis.session.Configuration类的databaseId获取

你可以再测试一下，

如果你有现成的多数据源的测试用例，可以放到 sqlhelper-examples 下，3q

**Comment by HSPCode** [comment]
> @HSPCode
> 
> 昨晚加了一个参数，来控制是否从org.apache.ibatis.session.Configuration类的数据库Id获取
> 
> 你可以再测试一下，
> 
> https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-dialect/src/main/java/com/jn/sqlhelper/dialect/instrument/SQLInstrumentorConfig.java
> 
> 如果你有现成的多数据源的测试用例，可以放到sqlhelper-examples下，3q
> 如果没有的话，我就后续加个测试用例

①之前描述的有点问题，org.apache.ibatis.session.Configuration类的databaseId获取的是yml文件spring.datasource.dynamic.primary指明的默认数据源，不是第一个数据源。原因是，dynamic的com.baomidou.dynamic.datasource.toolkit.DynamicDataSourceContextHolder类的peek()方法会返回当前线程/代码使用的数据源名称，但是项目启动的时候是没有使用数据源的，peek()返回空，之后的逻辑操作使用primary指定的默认数据源，即使用primary指定的数据源处理为Configuration类的databaseId；
详见：org.mybatis.spring.SqlSessionFactoryBean类的buildSqlSessionFactory方法
![image](https://user-images.githubusercontent.com/47849395/96968542-b34b9800-1543-11eb-8e14-c587132d242f.png)
com.jn.sqlhelper.common.utils.Connections类的getDatabaseProductName方法：
![image](https://user-images.githubusercontent.com/47849395/96968784-0f162100-1544-11eb-8c5b-40a9e5b50d7e.png)
这一步实际获取的是primary指定的数据源的conn；

②SQLHelper获取databaseId的地方是，com.jn.sqlhelper.mybatis.MybatisUtils类的getDatabaseId方法，
![image](https://user-images.githubusercontent.com/47849395/96967222-bf365a80-1541-11eb-95ae-afa73435d49b.png)
只在红框的地方获取到了databaseId，所以导致SQLHelper分页处理（查找Dialect）都按照primary数据源类型来处理了。


其实问题就是，MybatisUtils的getDatabaseId方法，在集成dynamic多数据源的情况下前几步都没获取到databaseId。

**Comment by fangjinuo** [comment]
我理解的，那我在configuration上加了开关后，确保不走configuration的方式获取，也就是走最后的方式，应该没有问题吧。因为最后的方式就是从真实的数据源里过去的。

**Comment by HSPCode** [comment]
最后的方式是连接数据源呀，虽然可以但是性能方面肯定不友好呀，相当于每次查询数据库之前，多连接一次数据库呀。
现在我本地代码的处理方式是覆盖了你的MybatisUtils方法的getDatabaseId方法，具体如代码所示：



入参MappedStatement ms其实是可以获取到dynamic配置的多数据源信息的。


大佬你看SQLHelper框架能优化下嘛。

**Comment by fangjinuo** [comment]
不会多连接的，如果每次都多连接一次，还要线程池有什么意义呢？你可以看到TX. getconnection的实现都是没有connection情况下才会去创建

**Comment by HSPCode** [comment]
嗯嗯，好的，受教了。当时没往连接池这块想，TX.getConnection也没看过源码，这就去看

**Comment by fangjinuo** [comment]
虽然他们开发的 dynamic-datasource 工具比较好用，但是有一种情况处理不了。
```
SQL mapper 文件中，为sql 定义 指定了 databaseId 属性的场景下用不了。
原因： 
mybatis Configuration对象在初始化时，会通过默认关联的datasource, 来解析 出默认的databaseId，
然后在解析所有的 sql mapper的过程中，发现了自定义的databaseId 和 默认的databaseId 不一样的话，是不会 care的。
内部是Map结构存储了所有的SQL , key 是namespace+sqlid，所以同sqlid的，只会保留一个。
```

解决方案：
```
创建多个 Configuration , Configuration 和SQLSessionFactory是一 一对应的，所以要创建多个SqlSessionFactory，
并自定义 自己的SqlSessionTemplate ，在自定的SqlSessionTemplate 中，可以通过反射拿到注解来自动的切换 sqlsessionfactory，从而达到切换 datasource的能力
```

**Comment by lishuanghe214** [comment]
不支持多数据源，request.getResult()返回为空

**Comment by fangjinuo** [comment]
@HSPCode 
@yaozhigangyeah 

sqlhelper 提供了多数据源配置方案，如有需要，可以试用。
