### ISSUE TITLE
我的多数据源配置不生效，分页信息都没传到sql里

### ISSUE THREAD

**Issue by yaozhigangyeah** [fangjinuo/sqlhelper#139]
我的多数据源是这样配置的，不用切换
@Configuration
@MapperScan(basePackages = "com.lingdong.business.mapper,com.lingdong.mapper",sqlSessionTemplateRef ="firstSqlSessionTemplate")
public class FirstDataSourceConfig {

    @Autowired
    private FirstDataBaseProperties prop;

    /**创建数据源*/
    @Bean(name = "firstDS")
    @ConfigurationProperties(prefix = "spring.datasource.first")
    @Primary
    public DataSource getFirstDataSource() {
        DruidDataSource dataSource = new DruidDataSource();
        dataSource.setDriverClassName(prop.driverClassName);
        dataSource.setUrl(prop.url);
        dataSource.setUsername(prop.username);
        dataSource.setPassword(prop.password);

        return dataSource;
    }

    /**创建SessionFactory*/
    @Bean(name = "firstSqlSessionFactory")
    @Primary
    public SqlSessionFactory firstSqlSessionFactory(@Qualifier("firstDS") DataSource dataSource) throws Exception {
        SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
        bean.setDataSource(dataSource);
        bean.setTypeAliasesPackage("com.lingdong.bean,com.lingdong.bean.business");

        Resource[] mapperLocations1 = new PathMatchingResourcePatternResolver().getResources("classpath*:mapper/*.xml");
        Resource[] mapperLocations2 = new PathMatchingResourcePatternResolver().getResources("classpath*:business/mapper/*.xml");
        Resource[] mapperLocations = new Resource[mapperLocations1.length+mapperLocations2.length];
        int inx = 0;
        for(Resource r:mapperLocations1){
            mapperLocations[inx++] = r;
        }
        for(Resource r:mapperLocations2){
            mapperLocations[inx++] = r;
        }
        bean.setMapperLocations(mapperLocations);

        return bean.getObject();
    }

**Comment by fangjinuo** [comment]
你这样，分页就没有生效

你先看一下 https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-mybatis-spring-boot/sqlhelper-mybatis-spring-boot-autoconfigure/src/main/java/com/jn/sqlhelper/mybatis/spring/boot/autoconfigure/SqlHelperMybatisAutoConfiguration.java 这个类做了什么，就明白了

**Comment by yaozhigangyeah** [comment]
那应该怎样配置多数据源，是要配置成动态切换吗

**Comment by fangjinuo** [comment]
![DBB71CE5-9702-4fa6-B8FF-A5FEA3B96E11](https://user-images.githubusercontent.com/8428331/84980042-96e9ba00-b163-11ea-9ae6-9943cc2f4144.png)

针对你这种，自定义 SqlSessionFactory的场景，可以这么做

**Comment by yaozhigangyeah** [comment]
this.sqlHelperMybatisProperties怎么来的

**Comment by fangjinuo** [comment]
springboot application.yml，有默认值，可以不配置

**Comment by fangjinuo** [comment]
可以去看看sqlhelper-examples 中的例子
