### ISSUE TITLE
插件适用性问题有严重BUG

### ISSUE THREAD

**Issue by ajiu-100wb** [fangjinuo/sqlhelper#141]
Method threw 'java.lang.RuntimeException' exception. Cannot evaluate com.jn.sqlhelper.dialect.pagination.PagingRequest.toString()

无论我如何尝试，是直接适用其插件，还是配合springboot ，或者是兼容pageH都会给我报这种错误在执行第一行分页就会抛出

 PagingRequest request1 = new PagingRequest().setPageNo(currentPage).setPageSize(pageSize);
 PagingRequest request = SqlPaginations.preparePagination(currentPage == 0 ? 1 : currentPage, pageSize == 0 ? -1 : pageSize, "DESC");
        
我在想你们是如何使用其插件的？？？

**Comment by fangjinuo** [comment]
你看一下 sqlhelper-examples中的例子

**Comment by ajiu-100wb** [comment]
那个只是提示不会真的报错，真正的原因是getResult永远是空，已经反复看过你的样例

**Comment by ajiu-100wb** [comment]
我先说一下我的配置
项目构建是gradle
1.加入依赖
    compile 'com.github.fangjinuo.sqlhelper:sqlhelper-jsqlparser:3.1.1'
    compile 'com.github.fangjinuo.sqlhelper:sqlhelper-dialect:3.1.1'
    compile 'com.github.fangjinuo.easyjson:easyjson-jackson:3.0.0'
2.运行分页代码
PagingRequest request = SqlPaginations.preparePagination(currentPage, pageSize);
        PagingRequestContextHolder.getContext().setPagingRequest(request);
        List<User> x= mapper.list(xx, xx);
System.out.println(request.getResult()); 这一步永远为空！！！！

**Comment by ajiu-100wb** [comment]
最后说一下我使用的结果。
1. 添加依赖
  compile group: 'com.github.fangjinuo.easyjson', name: 'easyjson-jackson', version: '3.0.0'
    compile group: 'com.github.fangjinuo.sqlhelper', name: 'sqlhelper-mybatis-spring-boot-autoconfigure', version: '3.1.1'
    compile group: 'com.github.fangjinuo.sqlhelper', name: 'sqlhelper-mybatis-spring-boot-starter', version: '3.1.1'
2. 修改mybaties.xml配置文件，这块有点坑，作者应该给予告知修改后的方法指向，导致我重试N次才发现方法被移动到了别处
<settings>
        <setting name="defaultScriptingLanguage" value="com.jn.sqlhelper.mybatis.plugins.CustomScriptLanguageDriver" />
    </settings>

    <plugins>
        <plugin interceptor="com.jn.sqlhelper.mybatis.plugins.SqlHelperMybatisPlugin"/>
    </plugins>
3. 调用分页代码就可以了这些没什么问题

**Comment by fangjinuo** [comment]
![image](https://user-images.githubusercontent.com/8428331/88383392-02671d00-cddd-11ea-9e65-53aa6ef6cf2f.png)

**Comment by fangjinuo** [comment]
我调试看了，正常的呀

**Comment by fangjinuo** [comment]
想起来了，你要只用mybatis的话，需要手动配置插件类，另外类名可能做了调整，注意一下。
