### ISSUE TITLE
com/jn/sqlhelper/dialect/instrument/SQLStatementInstrumentor类countSql方法多截取原始sql的非order by部分导致count sql语句错误

### ISSUE THREAD

**Issue by wangjiagoo** [fangjinuo/sqlhelper#145]
https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-dialect/src/main/java/com/jn/sqlhelper/dialect/instrument/SQLStatementInstrumentor.java

**Describe the bug**
如果sql语句前面有空格，并且包含 order by语句，在生成count sql的时候，会多截取原始sql的非order by部分。

**To Reproduce**
1. 使用类似的在select前面包含空格的sql：  "  select * from table where 1=1 order by a "，
2. 使用：
PagingRequest request = SqlPaginations.preparePagination(pageIndex ==null ?(Integer)parameterMap.get("pageIndex") : pageIndex, (Integer)parameterMap.get("pageSize"));
分页查询会出现错误

![image](https://user-images.githubusercontent.com/10148965/90753522-4cbfb900-e30b-11ea-857b-6b91dfb86d49.png)
![image](https://user-images.githubusercontent.com/10148965/90753892-be980280-e30b-11ea-9dc2-21db2814db81.png)

问题应该上图中，在计算 order 部分index时没有trim，但是截取的时候 trim，引起错误。

项目中发现这个问题，目前已要求用户注意sql语句最前面不要包含空格，暂时规避这个bug。
希望能修复。谢谢。

**Comment by fangjinuo** [comment]
3q
会尽快修复

**Comment by fangjinuo** [comment]
问题已修复，最近几天就给出补丁，请耐心等待

**Comment by wangjiagoo** [comment]
谢谢了，升级后没有这个问题了。

**Comment by fangjinuo** [comment]
> 谢谢了，升级后没有这个问题了。

后面使用过程中，有啥问题，尽管提
