### ISSUE TITLE
Method threw 'java.lang.RuntimeException' exception. Cannot evaluate com.jn.sqlhelper.dialect.pagination.PagingRequest.toString()

### ISSUE THREAD

**Issue by ducp123** [fangjinuo/sqlhelper#147]
PagingRequest request = SqlPaginations.preparePagination(page ,limit);调用这个方法的时候报错如下；
Method threw 'java.lang.RuntimeException' exception. Cannot evaluate com.jn.sqlhelper.dialect.pagination.PagingRequest.toString()

**Comment by fangjinuo** [comment]
该问题发生在你主动调用 toString方法时，SqlPaginations.preparePagination(page ,limit); 这个调用是不会出现该问题的。

**Comment by fangjinuo** [comment]
resolved at version 3.2.2
