### ISSUE TITLE
大佬后期能兼容下pagehelper-spring-boot嚒？

### ISSUE THREAD

**Issue by wuzhenxi520** [fangjinuo/sqlhelper#149]
兼容pagehelper的maven引用
<dependency>
    <groupId>com.github.fangjinuo.sqlhelper</groupId>
    <artifactId>sqlhelper-mybatis-over-pagehelper</artifactId>
    <version>3.2.1</version>
</dependency>
在pagehelper-spring-boot中不凑效
子查询[PAGING_START] [PAGING_END]sql无法识别，代码子查询已开，数据库是postgresql，是我配置不对嚒？
PagingRequest request = SqlPaginations.preparePagination(1, 10);
request.subqueryPaging(true);
SqlPaginations报错
Method threw 'java.lang.RuntimeException' exception. Cannot evaluate com.jn.sqlhelper.dialect.pagination.PagingRequest.toString()

**Comment by fangjinuo** [comment]
子查询的例子，看这里：
https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-examples/sqlhelper-examples-service/sqlhelper-examples-service-mybatis/src/main/java/com/jn/sqlhelper/examples/mybatis/controller/UserController.java

另外，pagehelper-spring-boot 没有毕业做兼容，既然要从pagehelper切换到sqlhelper， pagehelper-spring-boot 本身就应该废弃了。

PagingRequest.toString() 这个代码运行时不建议调用
