### ISSUE TITLE
请问一下， 支持sql语法解析吗？

### ISSUE THREAD

**Issue by yh2388** [fangjinuo/sqlhelper#150]
支持表级别、列级别的语法解析吗？
支持的数据库有哪些，例如rmdbs、hive等

**Comment by fangjinuo** [comment]
已支持的数据库见这里：
https://github.com/fangjinuo/sqlhelper/wiki/Pagination_Database

**Comment by yh2388** [comment]
> https://github.com/fangjinuo/sqlhelper/wiki/Pagination_Database

多谢， 如果我要使用sql语法解析的功能，应该使用哪个模块或者类来操作？

**Comment by fangjinuo** [comment]
> > https://github.com/fangjinuo/sqlhelper/wiki/Pagination_Database
> 
> 多谢， 如果我要使用sql语法解析的功能，应该使用哪个模块或者类来操作？

如果你想直接使用语法解析的功能，可以使用 jsqlparser 这个类库 (https://github.com/JSQLParser/JSqlParser)
