### ISSUE TITLE
SqlServer2012 分页处理语法错误

### ISSUE THREAD

**Issue by wangjiagoo** [fangjinuo/sqlhelper#156]
**Describe the bug**
使用jdbc连接SqlServer2012，在分页处理时，自动获取到的数据库方言为：com.jn.sqlhelper.dialect.internal.SQLServerDialect.SQLServer2012Dialect
该方言处理分页语句的LimitHandler 使用 com.jn.sqlhelper.dialect.internal.limit.OffsetFetchFirstOnlyLimitHandler，生成的分页sql如果为第一页，会抛出语法错误

**To Reproduce**
1. 使用jdbc连接SqlServer2012
2. 使用如下的代码
![image](https://user-images.githubusercontent.com/10148965/100711017-a005d500-33eb-11eb-9771-6bc6270c7369.png)

3. 在 FETCH 语句中选项 first 的用法无效

**问题分析**
1. 查看源码，问题出现在com.jn.sqlhelper.dialect.internal.limit.OffsetFetchFirstOnlyLimitHandler 的String getLimitString(String sql, long offset, int limit)方法中：
2. 
![image](https://user-images.githubusercontent.com/10148965/100711291-07238980-33ec-11eb-9511-8c062eee05b8.png)
        if (getDialect().isUseLimitInVariableMode()) {
            if (hasOffset) {
                sql2.append(" OFFSET ? ROWS FETCH NEXT ? ROWS ONLY");
            } else {
                sql2.append(" FETCH FIRST ? ROWS ONLY");
            }
        } else {
            if (hasOffset) {
                sql2.append(" OFFSET " + offset + " ROWS FETCH NEXT " + limit + " ROWS ONLY");
            } else {
                sql2.append(" FETCH FIRST " + limit + " ROWS ONLY");
            }
        }
此时hasOffset为false
执行：
![image](https://user-images.githubusercontent.com/10148965/100711590-739e8880-33ec-11eb-81d5-721278ef38dc.png)

3. 例如，原始sql ：select * from bm_equipment_type order by gid
  处理之后的分页sql: select * from bm_equipment_type order by gid fetch first 500 rows only
 执行后会出错：
![image](https://user-images.githubusercontent.com/10148965/100711768-b95b5100-33ec-11eb-8c16-afef4623b0c2.png)
正确的分页sql： select * from bm_equipment_type order by gid OFFSET 0 ROWS fetch first 500 rows only
![image](https://user-images.githubusercontent.com/10148965/100711909-e9a2ef80-33ec-11eb-884b-eaa7dfad2658.png)

4. OffsetFetchFirstOnlyLimitHandler也在其他数据库中使用，这里只是发现在SqlServer2012中会出现问题，
   不能去掉offset x rows， 修复时可能需要考虑在其他数据库或者版本中的表现。

**暂时解决**
1.暂时通过修改全局的instrumentor配置，使用sqlserver2005方言

![image](https://user-images.githubusercontent.com/10148965/100712586-f247f580-33ed-11eb-9729-2edb1d53093c.png)

2.这种方式会导致全局都使用 sqlserver2005方言，没法在同一个应用中方便的连接不同类型的数据库。

**Comment by fangjinuo** [comment]
@wangjiagoo 

感谢提此问题，以及对此问题的分析非常到位，为你点赞。

问题已修复： 5bc71b77dded9d5256ee4d422114b9a45582be85

目前尚未打包，可以自行打包测试。
