### ISSUE TITLE
DatabaseDescription 报错nullpoint

### ISSUE THREAD

**Issue by jcm951301435** [fangjinuo/sqlhelper#157]
DatabaseDescription 类中方法supportsCatalogsInTableDefinitions() 是否应当先判断supportsCatalogsInTableDefinitions==null
![image](https://user-images.githubusercontent.com/38455583/101118841-e3975380-3624-11eb-936d-61f29edc8a47.png)

**Comment by fangjinuo** [comment]
你说的对。已修复 390c98bc348ee0e4aabc357bc2b5f49d005a37e9
