### ISSUE TITLE
关于ddl生成，是否可以支持生成不同数据库的ddl语句

### ISSUE THREAD

**Issue by jcm951301435** [fangjinuo/sqlhelper#158]
需求: 获取oracle数据库表结构，在mysql中生成此表。
sqlhelper-dialect可以导出ddl语句(使用CommonTableGenerator类)
但目前生成的字段类型为源数据库的类型：如oracle 数据库VARCHAR2, 生成DDL语句时固定为VARCHAR2。
是否可以根据传入的数据库类型及column 的JdbcType 自动判断typeName。
补充:
AbstractTableGenerator 类中`buildDefineColumnClause(table, column)`
 `builder.append(column.getName()).append(" ").append(column.getTypeName());`
此处`column.getTypeName()`是否可以根据`JdbcType`与`DatabaseDescription`动态生成

**Comment by fangjinuo** [comment]
当时设计时，就是支持后续扩展的：
![image](https://user-images.githubusercontent.com/8428331/101129102-f23d3500-363b-11eb-919f-f58769441563.png)

如果想要针对的处理，继承 CommonTableGenerator或 AbstractTableGenerator ，然后定制化实现即可。
