### ISSUE TITLE
kingbase数据库分页问题

### ISSUE THREAD

**Issue by HSPCode** [fangjinuo/sqlhelper#161]
数据库是kingbase，使用SQLHelper分页时获取了错误的limit，导致从第二页开始分页结果不对。

**To Reproduce**
pageNum>=2即可复现

**Expected behavior**
正常分页

**Screenshots**
package：com.jn.sqlhelper.dialect.internal.limit
class：LimitOffsetLimitHandler
![image](https://user-images.githubusercontent.com/47849395/106840835-e6253080-66db-11eb-9f34-e88451be8251.png)

计算limit
package：com.jn.sqlhelper.dialect.internal.limit
class：AbstractLimitHandler
![image](https://user-images.githubusercontent.com/47849395/106840889-00f7a500-66dc-11eb-8dca-d8605568dd4d.png)

![image](https://user-images.githubusercontent.com/47849395/106841063-4ddb7b80-66dc-11eb-943e-288302d8ebb9.png)
isUseMaxForLimit方法固定返回true，导致limit变为limit + firstRow，而实际只需要limit本身即可。另外能问下isUseMaxForLimit这个方法是干什么的吗？

**Additional context**
kingbase依赖版本：8.2.0
SQLHelper依赖版本：3.2.2

**Comment by fangjinuo** [comment]
升级到 sqlhelper 3.4.8 即可

另外能问下isUseMaxForLimit这个方法是干什么的吗？
答：有的数据库是 limit endrow，有的数据库是 limit count

**Comment by HSPCode** [comment]
> 升级到 sqlhelper 3.4.8 即可
> 
> 另外能问下isUseMaxForLimit这个方法是干什么的吗？
> 答：有的数据库是 limit endrow，有的数据库是 limit count

嗯嗯，好的
