### ISSUE TITLE
与mybatis-plus3集成， @TableId注解无法使用

### ISSUE THREAD

**Issue by zhushenggao** [fangjinuo/sqlhelper#162]
使用mybatis-plus最新版本3.4.2
使用sqlhelper最新版本3.4.8
![image](https://user-images.githubusercontent.com/11799914/110097811-5dabb580-7d97-11eb-8108-8ea65d367d9b.png)
无法使用注解来生成UUID
![image](https://user-images.githubusercontent.com/11799914/110097363-d6f6d880-7d96-11eb-8e6c-76853d92eb17.png)
需要如何处理？

**Comment by fangjinuo** [comment]
3.4.9 版本之后已修复
