### ISSUE TITLE
3.5.0版本兼容mybatis-plus的问题

### ISSUE THREAD

**Issue by quhailong** [fangjinuo/sqlhelper#169]
3.5.0及以上版本好像不兼容高版本的mybatis-plus，你这个pom里面用的是<mybatis.plus_3x.version>3.1.2</mybatis.plus_3x.version>
我的项目里mybatis-plus-boot-starter版本为3.4.1
项目启动会报错：
![849a0909b3499579892b1a7cdc7ce7d](https://user-images.githubusercontent.com/26958237/117233140-1e601a80-ae55-11eb-8e60-3888c28a2d03.png)
希望能兼容一下

**Comment by fangjinuo** [comment]
兼容的吧， pom文件里可以看到测试了 多个 mybatis-plus版本：3.1.2， 3.2.0， 3.4.1， 3.4.2

**Comment by quhailong** [comment]
> 兼容的吧， pom文件里可以看到测试了 多个 mybatis-plus版本：3.1.2， 3.2.0， 3.4.1， 3.4.2
> 
> 另外，由于Mybatis-plus 内部代码，包名等等，在它的各个版本间，变更比较大，建议是 mybatis-plus 的自身的相关jar包选用一致版本。 sqlhelper 已经尽最大努力去做到兼容了

嗯，调整一下pom顺序就行了，sqlhelper放在mybatis-plus其他依赖后面就可以启动了
