### ISSUE TITLE
配置完sqlhelper，启动应用后出现JSON libraries问题

### ISSUE THREAD

**Issue by evanyangg** [fangjinuo/sqlhelper#67]
Can't find any supported JSON libraries : [gson, jackson, fastjson]

**Comment by fangjinuo** [comment]
sqlhelper依赖了 easyjson库，而easyjson是一个json库适配器，可以将任何的json库适配给gson, jackson, fastjson三者之一 。

所以你的程序中，需要有 gson, jackson, fastjson 3者之一。
且需要使用 easyjson- xxx 进行适配。
例如使用 easyjson-gson 来适配给 gson
