### ISSUE TITLE
排序入参问题

### ISSUE THREAD

**Issue by evanyangg** [fangjinuo/sqlhelper#68]
数据库字段为user_id
业务中字段为驼峰userId
前端给后端的key值肯定是userId
PagingRequest request = new PagingRequest()
                // 会报错
                .limit(1 ,2).setOrderBy(SqlStyleOrderByBuilder.DEFAULT.build("userId desc"));
                // 正常
                .limit(1 ,2).setOrderBy(SqlStyleOrderByBuilder.DEFAULT.build("user_id desc"));
可否有相关配置来确定数据库字段和业务中对象属性之间的转换关系呢？

**Comment by fangjinuo** [comment]
提供了SqlSymbolMapper接口，用于进行symbol 转换，同时也提供了两个实现类，另外你也可以自定义实现。
提供的两个实现类：
1. com.jn.sqlhelper.dialect.symbolmapper.NoopSymbolMapper  这是实现类什么也不做，且它是默认的
2. com.jn.sqlhelper.dialect.symbolmapper.CamelToUnderlineSymbolMapper  这个实现类可以根据大写字母进行分割


相关测试用例参见：
1. com.jn.sqlhelper.tests.SqlStyleOrderByBuilderTests
2. com.jn.sqlhelper.tests.CamelToUnderlineSymbolMapperTests

**Comment by evanyangg** [comment]
@fangjinuo 你好，我们原来只用了一个PageInterceptor，但是发现$作为入参会有问题，后来预研了pageHelper mybatis-plus，但是感觉太重了，pageHelper 又返回了很多无用参数，而且只会对mapper有效，调用service时，总页数和总记录数无法正确返回。
所以我想问的是，sqlHelper 我作为生产环境有问题吗？该项目的稳定情况。
还有就是如果多条件排序的话 现在我只能通过 "user_id desc and create_tiem desc" 入参来解决。
是否可以一个方法接受排序参数然后另外一个方法执行排序类型呢？
例如
("user_id").desc().("create_tiem").desc()
这样的语法会不会更好一些呢？

**Comment by fangjinuo** [comment]
@evanyangg 
关于稳定性：目前已经在我司多个项目中使用，可以放心使用。
关于Bug：即便发现什么问题，及时联系我，也可以尽快修复。
关于 orderby 不方便的问题，会尽快出一个OrderByBuilder，当然了你们也可以自己扩展的

**Comment by fangjinuo** [comment]
@evanyangg 
you can see [ProgramStyleOrderByBuilder](https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-dialect/src/main/java/com/jn/sqlhelper/dialect/orderby/ProgramStyleOrderByBuilder.java)

it's test cases:
1. [ProgramStyleOrderByBuilderTests](https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-dialect/src/test/java/com/jn/sqlhelper/tests/ProgramStyleOrderByBuilderTests.java)
1. [MemoryPaginationsTests](https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-dialect/src/test/java/com/jn/sqlhelper/tests/MemoryPaginationsTests.java)

**Comment by evanyangg** [comment]
@fangjinuo 非常给力👍👍👍，坐等新版本！
