### ISSUE TITLE
命名建议

### ISSUE THREAD

**Issue by evanyangg** [fangjinuo/sqlhelper#69]
PagingRequest request = new PagingRequest()
这个是sqlhelper的对象，
其实在服务器端开发中，经常会用到HttpServletRequest 
也经常会命名为request,
感觉会容易混淆，能否有明显的区分呢？

**Comment by fangjinuo** [comment]
你说的这个就属于个人的编码习惯了， 
你可以不命名为request的，例如：
1. PagingRequest paging= new PagingRequest()
2. PagingRequest sqlRequest= new PagingRequest()
等等
