### ISSUE TITLE
是否可以细化下spring boot的配置文档

### ISSUE THREAD

**Issue by alenX** [fangjinuo/sqlhelper#73]
目前文档中描述的Spring Boot的[配置描述](https://github.com/fangjinuo/sqlhelper/wiki/Pagination_QuickStart_MyBatis)
实际[example配置](https://github.com/fangjinuo/sqlhelper/blob/master/sqlhelper-examples/pom.xml#L89)，并不是很一致，特别是对于从pagehelper迁移的步骤，谢谢

**Comment by fangjinuo** [comment]
example 是为了测试各种应用情况的，所以各种情况的Java包都会被依赖。

step 1: remove mybatis-pageHelper dependency
step 2: import sqlhelper's:
  1. sqlhelper-mybatis
  2. sqlhelper-mybatis-spring-boot-autoconfigure
  3. sqlhelper-mybatis-spring-boot-starter
  4. sqlhelper-mybatis-over-pagehelper

**Comment by alenX** [comment]
ok i will give it a shot,3q

**Comment by alenX** [comment]
```xml
       <dependency>
            <groupId>com.github.fangjinuo.easyjson</groupId>
            <artifactId>easyjson-jackson</artifactId>
            <version>${easyjson.version}</version>
        </dependency>
```

**Comment by fangjinuo** [comment]
已经加了个FAQ
